### ISSUE TITLE
Removing requirement for view controllers in storyboards

### ISSUE THREAD

**Issue by kerrmarin** [deanWombourne/Scenic#1]
I have an app I'm building that I use Scenic in. The app uses UIKit/Scenic to manage navigation but all (or at least most) views are written in SwiftUI. This leaves me with view controllers that are very simple e.g.:

```swift
final class LoginViewController: UIViewController {

    private var loginView: LoginView! // a SwiftUI view

    var viewModel: LoginViewModel! {
        didSet {
            self.loginView = LoginView(viewModel: self.viewModel)
        }
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.embedChildView(self.loginView)
    }
}
```

I like using this arch because it gives me the best control over navigation and appearance and allows me to quickly prototype/build UIs.

The problem I have is that I end up creating a storyboard file that always has just an empty view controller so scenic can instantiate my VC. I'd like to stop having these files around in my project.

From what I can see, there's two obvious ways of doing this:

1. try/catch any exception when instantiating the view controller via storyboard and instead instantiate the VC via its `init` method, something like:

```swift
    func createViewControllerFromSceneStoryboard(in bundle: Bundle?) -> ViewControllerType {
        do {
            return try ViewControllerType.instantiateFromStoryboard(named: self.sceneName, bundle: bundle)
        } catch {
            return ViewControllerType()
        }
    }
```

however the try/catch mechanism would have to be obj-c since the exception thrown when instantiating a view controller via a storyboard is in objc.

2. Pass in some sort of flag to each `Scene` that indicates whether to use storyboards or the initialiser. Something like:

```swift
public enum InitialisationSource {
    case storyboard
    case constructor
}
```

in the Scene protocol add `var initialisationSource: InitialisationSource { get }` with a default implementation to return `.storyboard` for backwards compatibility and then:

```swift
    func createViewControllerFromSceneStoryboard(in bundle: Bundle?) -> ViewControllerType {
        switch self.initialisationSource {
        case .constructor:
            return ViewControllerType()
        case .storyboard:
            return ViewControllerType.instantiateFromStoryboard(named: self.sceneName, bundle: bundle)
        }
    }
```

Any other options? Happy to make a PR just want to get your opinion on whether this is a change you're likely to accept before I start

**Comment by deanWombourne** [comment]
The `Scene` protocol has two methods - the configure method which you have to implement, and a `createViewController` method which has a default implementation to load from a Storyboard. You can override this method in your scene to just return a controller directly - then the Scene doesn't look for a storyboard.

i.e.

```swift
struct MyScene: Scene {

    func createViewController() -> MyViewController {
        MyViewController()
    }

    func configure(controller: MyViewController,
                   using factory: SceneFactory<MyFactoryContext>,
                   context: MyFactoryContext) {
    ...
}
```

**Comment by kerrmarin** [comment]
welp, should've RTFM

**Comment by deanWombourne** [comment]
In your defence, this project is missing a M :)
